small perf improvements to TriangulateSpade
georust/geo pull request #1122
Opened 2023-12-05 17:00 UTC by michaelkirk

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Bench output:
```
TriangulateSpade (unconstrained)
                        time:   [8.8442 ms 8.8522 ms 8.8619 ms]
                        change: [-2.9583% -2.7775% -2.6122%] (p = 0.00 <
0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) high mild
  3 (3.00%) high severe

TriangulateSpade (constrained)
                        time:   [8.9126 ms 8.9274 ms 8.9444 ms]
                        change: [-2.4017% -2.1584% -1.9066%] (p = 0.00 <
0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high severe

TriangulateEarcut       time:   [6.9632 ms 6.9750 ms 6.9883 ms]
                        change: [-1.0174% -0.7692% -0.5114%] (p = 0.00 <
0.05)
                        Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
```

Note this is an internal API, so we can safely break the API.

2023-12-05 20:16 UTC, urschrei approved these changes
Interested to hear how you came up with it, but lgtm.

2023-12-06 02:18 UTC, frewsxcv approved these changes

2023-12-06 08:23 UTC, RobWalt approved these changes
Super nice! Thanks for taking a shot at it, you nailed it 🎯

2023-12-06 15:52 UTC, RobWalt requested changes

2023-12-06 15:52 UTC, RobWalt commented on geo/benches/triangulate.rs
> +                let triangulation = TriangulateSpade::unconstrained_triangulation(poly).unwrap();
A friend of mine just pointed out that both benchmarks do the same thing since they both use the `unconstrained_triangulation` method

2023-12-07 08:40 UTC, RobWalt approved these changes

2023-12-07 17:15 UTC, merged