Add `DensifyGeodesic` trait
georust/geo pull request #1208
Opened 2024-08-10 19:43 UTC by grevgeny

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

This PR adds `DensifyGeodesic` trait that follows logic similar to `DensifyHaversine`. However, the trait is only implemented for `T = f64` as underlying Geodesic traits are implemented only for this type.

2024-08-12 23:38 UTC, michaelkirk requested changes
I have some minor nits, but overall it looks good. Thank you!

2024-08-12 23:38 UTC, michaelkirk commented on geo/src/algorithm/densify_geodesic.rs
> +    fn densify_geodesic(&self, max_distance: F) -> Self::Output;
```suggestion
    fn densify_geodesic(&self, max_meters: f64) -> Self::Output {
```

I know it's in the docs, but it's nice to be redundant sometimes.

2024-08-12 23:38 UTC, michaelkirk commented on geo/src/algorithm/densify_geodesic.rs
> +
Can you add a test where `max_meters` is larger than each of the segment lengths?   i.e. where the algorithm is a no-op.

2024-08-12 23:38 UTC, michaelkirk commented on geo/src/algorithm/mod.rs
> +/// Densify geometry components on a spheroid;
```suggestion
/// Densify geometry components on a geodesic.
```

nit: period, not semicolon.

And I don't know that it's better, but "geodesic"  is consistent with our other doc strings, so let's use it everywhere.

2024-08-13 18:02 UTC, grevgeny commented
@michaelkirk thanks for your review! I have added proposed changes

2024-08-13 18:35 UTC, michaelkirk commented
I think you'll need to run cargo fmt, otherwise LGTM

I'll leave it open for a couple days before merging in case anyone else wants to weigh in.

2024-08-20 01:31 UTC, michaelkirk commented
Darn it. I'm sorry for not realizing this earlier. This seems related to https://github.com/georust/geo/issues/1181

2024-09-26 18:10 UTC, michaelkirk commented
Assuming #1216 gets merged, I've got a different approach that should supersede this, generically implementing Densify for all line measures (Haversine, Geodesic, Euclidean, etc.)

You can see a WIP here: https://github.com/georust/geo/compare/mkirk/unify-densify?expand=1

2024-10-23 00:19 UTC, michaelkirk commented
My alternative to this was merged in #1231.

With that you can call:
```rust
use geo::{Geodesic, Densify, Euclidean};
line_string.densify::<Geodesic>();
line_string.densify::< Euclidean >();
```

Let me know if that works for your purposes @grevgeny.

2024-10-23 00:19 UTC, closed without merging

2025-02-05 22:52 UTC, michaelkirk commented
With #1298 (not yet released) this changed to:

```rust
use geo::{Geodesic, Densify, Euclidean};
Geodesic.densify(&line_string);
Euclidean.densify(&line_string);
```