feat: make `FrechetDistance` generic over Metric Spaces
georust/geo pull request #1274
Opened 2024-11-21 14:24 UTC by grevgeny

- [ ] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

2024-11-21 14:26 UTC, grevgeny commented
@michaelkirk What do you think about the following approach to `FrechetDistance` with new metric space setup for lines?

2024-12-03 12:39 UTC, lnicola commented
This is only a drive-by comment, but wouldn't it make sense to pass the metric as a value, e.g. `g1.frechet_distance(&Euclidean, g2)`? I think some metrics can be parameterized, like Mahalanobis, which takes a point and a covariance matrix.

2024-12-03 21:04 UTC, lnicola commented
We could go directly for `Euclidean.frechet_distance(&line_string_1, &line_string`, then.

2024-12-03 21:40 UTC, lnicola commented
Yeah, something like that. In my example, `Euclidean` is an empty struct, and there's a single trait method, which takes `&self`. I imagine we could also make constants for the more common parameterizations.

2024-12-03 21:55 UTC, michaelkirk commented
Euclidean isn't a very illuminating example, because I don't think you'd ever want to customize it, so let's talk about Haversine.

... maybe this would be better:
```rust
trait FrechetDistance: Distance<Point, Point> {
  fn frechet_distance(&self, lhs: &LineString, rhs: &LineString) -> F {
     // more or less the same impl as it exists today
  }
}

pub struct Haversine;
pub struct CustomHaversine { radius_meters: f64 };

impl Haversine {
  pub fn with_radius(radius_meters: f64) -> CustomHaversine {
    // Is it weird that this returns something other than `Self`?
    CustomHaversine { radius_meters }
  }
}

impl Distance<Point, Point> for CustomHaversine {
  fn to_radians(degrees: f64) -> f64 {
    degrees * PI / 180.0
  }
  fn distance(&self, lhs: &Point, rhs: &Point) -> F {
     let lat1 = Self::to_radians(lat1);
     let lon1 = Self::to_radians(lon1);
     let lat2 = Self::to_radians(lat2);
     let lon2 = Self::to_radians(lon2);

     let dlat = lat2 - lat1;
     let dlon = lon2 - lon1;

     let a = (dlat / 2.0).sin().powi(2) + lat1.cos() * lat2.cos() * (dlon / 2.0).sin().powi(2);
     let c = 2.0 * a.sqrt().atan2((1.0 - a).sqrt());

     self.radius_meters * c  
  }
}

impl Distance<Point, Point> for Haversine {
 fn distance(&self, lhs: &Point, rhs: &Point) -> F {
    CustomHaversine::default().distance(lhs, rhs)
  }
}

// stays concise for the vast majority (I think?) of people who don't want to customize anything
Haversine.frechet_distance(&line_string_1, &line_string)

// Offer a slightly more verbose API for the 0.5% of users who want to customize the metric space
let mars_haversine = Haversine::with_radius(3_389_500);
mars_haversine.frechet_distance(&line_string_1, &line_string)
```

vs. my [previous suggestion](https://github.com/georust/geo/pull/1274#issuecomment-2515597271), this would avoid the weird distinction between `custom_frechet_distance` and `distance`. For something like Euclidean this distinction probably wouldn't even make sense.

Sorry to derail your PR review @grevgeny - it's kind of related though. 😅

2025-01-07 16:29 UTC, grevgeny commented
@michaelkirk @lnicola Thanks for your review! 

Should I then adjust my code based on your latest comment @michaelkirk ?

2025-01-07 17:11 UTC, michaelkirk commented
I'm not sure. I'm also looking for some design feedback on my proposal.

(/cc @lnicola too)

Do you think the approach I laid out above makes sense - I think it's what you were getting at @lnicola, but I wanted to use a non-euclidean example. 

It would be a breaking change to move all the recently introduced LineMeasure implementations from (e.g.) `Haversine::distance` to `Haversine.distance`, but maybe worth it for the functionality of being able to customize.

2025-01-11 01:17 UTC, michaelkirk commented
Sorry to keep you in a holding pattern @grevgeny. 

The reason I'm holding up the train is because I wanted to make some breaking changes to the line measures stuff to support customizable metric spaces.

Rather than release this, and then immediately break it, I'd prefer to make those API-breaking changes first, then adjust this PR.

I've just now opened the PR with those breaking changes here: #1298  - if/when that gets merged, I'd like to see this PR updated to look like:
```rust
Haversine.frechet_distance(line_string_1, line_string_2)
Euclidean.frechet_distance(line_string_1, line_string_2)
CustomHaversine::new(3_389_500.0).frechet_distance(line_string_1, line_string_2)
```

But maybe just hold off for now - I'm not sure how controversial #1298 will be. Feel free to weigh in over there.

2025-01-11 18:00 UTC, lnicola commented
> Do you think the approach I laid out above makes sense - I think it's what you were getting at @lnicola, but I wanted to use a non-euclidean example.

```rust
Haversine.frechet_distance(&line_string_1, &line_string_2);
Haversine::with_radius(3_389_500).frechet_distance(&line_string_1, &line_string_2);
```

I.. haven't given this much thought, but the following feel lighter to me compared to having both `Haversine` and `CustomHaversine`:

```rust
EARTH_HAVERSINE.frechet_distance(&line_string_1, &line_string_2);
// or
Haversine::default().frechet_distance(&line_string_1, &line_string_2);
// or
Haversine::earth().frechet_distance(&line_string_1, &line_string_2);

Haversine::with_radius(3_389_500.0).frechet_distance(&line_string_1, &line_string_2);
```

2025-01-13 19:15 UTC, lnicola commented
`Euclidean` doesn't need to be customizable, but I'd argue for `EUCLIDEAN`, for consistency. If we ever consider adding Mahalanobis (from my previous example), it could be argued it's more efficient to just transform the data. But the other three could, in principle, be customized.

While `Metric` / `CustomMetric` is a bit annoying to implement, it's not the end of the world either, and I guess we're unlikely to add a lot of other metrics.

2025-02-03 18:09 UTC, michaelkirk commented
Ok, #1298 has merged! (sorry for the delay)

Can you base this on what's now in master?

So I'd expect usage to look like:

```
Haversine.frechet_distance(&line_string_1, &line_string_2);
Euclidean.frechet_distance(&line_string_1, &line_string_2);
let mars = HaversineMeasure::new(mars_radius);
mars.frechet_distance(&line_string_1, &line_string_2);
```

2025-02-08 18:50 UTC, grevgeny commented
Sure! Thanks for the updates, I'll update the code accordingly

2025-02-09 16:00 UTC, grevgeny commented
PR is ready for review. 

@michaelkirk

2025-02-12 18:18 UTC, michaelkirk requested changes
This looks great! Just a couple minor house cleaning nits.

2025-02-12 18:18 UTC, michaelkirk commented on geo/src/algorithm/frechet_distance.rs
> +#[deprecated]
Please add a note referring them to the new callsite, `Euclidean::frechet_distance` - see other `deprecated` declarations in the repo for an example.

2025-02-12 18:18 UTC, michaelkirk commented on geo/src/algorithm/line_measures/frechet_distance.rs
> +                let dist = metric_space.distance(a, b);
I haven't scrutinized this implementation, but other than changing this `Euclidean.distance` to a generic `metric_space.distance`, it looks like it was just cut/pasted from the previous implementation.

Which is expected! :+1:

 But let me know if you've changed anything else in the impl that you'd like scrutinized.

2025-02-21 17:09 UTC, grevgeny commented on geo/src/algorithm/frechet_distance.rs
> +#[deprecated]
Fixed

2025-02-21 17:10 UTC, grevgeny commented on geo/src/algorithm/line_measures/frechet_distance.rs
> +                let dist = metric_space.distance(a, b);
You're right. The only thing changed is the distance calculation between points.

2025-02-21 19:24 UTC, michaelkirk approved these changes
Looks great! Wow, what a journey. Thanks for your patience!

2025-02-21 19:24 UTC, michaelkirk commented on geo/src/algorithm/frechet_distance.rs
> +    note = "Please use the `Euclidean.frechet_distance` method from the `geo::line_measures::FrechetDistance` trait instead"
perfect!

2025-02-21 19:29 UTC, merged